### ISSUE TITLE
byline w/ Node 0.10.16 emits buffers instead of strings

### ISSUE THREAD

**Issue by jvonniedapn** [jahewson/node-byline#17]
I'm not sure if you consider this a bug or not, but it broke one of my programs so I thought I'd submit it:

test.js

```
'use strict';

var
    fs = require('fs'),
    byline = require('byline');

var stream = byline(fs.createReadStream('test.txt'));

stream.on('data', function(line) {
    console.log(Buffer.isBuffer(line));
});
```

test.txt

```
one
two
a three
four
```

```
> node test
true
true
true
true
```

I had previously been using Node 0.10.3 and after upgrading to 0.10.16 I found that a function calling trim (from string) on line in the data event handler suddenly blew up. Turns out that under Node 0.10.3 the event emitted lines and in 0.10.16 it emitted Buffers.

**Comment by tssajo** [comment]
@irfaan : Probably because the curly braces were missing from the above post. It should look like this:

```javascript
var stream = byline(fs.createReadStream('test.txt', {encoding: 'utf8'}));
```

**Comment by tssajo** [comment]
Actually, this is what works for me:

```javascript
var stream = fs.createReadStream('test.txt', {encoding: 'utf8'});
stream = byline.createStream(stream);
```
