### ISSUE TITLE
`pipe` assumes `_readableState` is present

### ISSUE THREAD

**Issue by shimaore** [jahewson/node-byline#21]
The following fails:

    var request = require('request');
    var byline = require('byline');

    var stream = byline(request.get('http://www.google.com'));
    stream.on('end',function(){console.log('end')});
    stream.on('data',function(line){console.log(line+'\n')});

(using byline 4.1.1, request 2.27.0), with the following error:

    .../check-byline/node_modules/byline/lib/byline.js:75
          this.encoding = src._readableState.encoding;
                                            ^
    TypeError: Cannot read property 'encoding' of undefined
        at LineStream.<anonymous> (.../check-byline/node_modules/byline/lib/byline.js:75:41)
        at LineStream.EventEmitter.emit (events.js:95:17)
        at Request.Stream.pipe (stream.js:123:8)

Running with previous versions, byline 3.1.2 is the last one to work with this code.

**Comment by jahewson** [comment]
There's a lot of code out there still using old-style streams, which Byline wasn't handling correctly.
