### ISSUE TITLE
question please (insert parsed data to a DB)

### ISSUE THREAD

**Issue by mlotfi2005** [jahewson/node-byline#31]
Hi,
I am new here, I did some java work, we are looking to have a script to read huge comma separated file then insert it in a database, one of my coworkers talked about using python, I found your node.js project called node-byline 
please tell me if this code should work better than python ?
how to insert what was parsed to a database ?
thanks lot.

**Comment by jahewson** [comment]
Sorry, I can't really help you here. Byline can only read lines from a text file, if you're wanting to parse CSV then you'll need to look on [npm](https://www.npmjs.com/).
