### ISSUE TITLE
Better not to `console.log` while running

### ISSUE THREAD

**Issue by utensil** [jahewson/node-byline#33]
I'm writing a CLI program using `byline` and notice something like "LineStream encoding buffer" popped out in the console and it's caused by the following line in `lib/byline.js`:

```js
console.log('LineStream encoding %s', encoding);
```

I believe, as a library, it's better not to `console.log` while running, isn't it ? :wink:

**Comment by derhuerst** [comment]
bump

**Comment by jahewson** [comment]
That line of code doesn't exist.

**Comment by derhuerst** [comment]
[At `createLineStream`](https://github.com/jahewson/node-byline/blob/75639ed55bfdcc05fa2e43f5e0b62e394ad97fef/lib/byline.js#L41), you might want to use `console.warn` or write to `process.stderr`.

**Comment by derhuerst** [comment]
bump.
