### ISSUE TITLE
Browser complains about setImmediate() not being defined

### ISSUE THREAD

**Issue by cheton** [jahewson/node-byline#37]
The `setImmediate` function is defined within the Node.js timers module.
https://github.com/jahewson/node-byline/blob/master/lib/byline.js#L126

This can fix browser compatility without using global variables.
```js
var timers = require('timers');
 
timers.setImmediate(function() {
});
```

**Comment by jahewson** [comment]
Thanks, I've added this in fb2056b751ca82d2cbcbc33e23a256ff2db35007.
