### ISSUE TITLE
[Feature request] Ability to skip first line

### ISSUE THREAD

**Issue by lmammino** [jahewson/node-byline#46]
Hey @jahewson,
First of all thanks for all the effort you put in this amazing module. 

When processing CSV or TSV files it would be very handy to have an option to skip the first line.

E.g.

```javascript
import { createReadStream } from 'fs';
import byline from 'byline';

const sourceFile = 'somefile.csv';

byline.createStream(
  createReadStream(sourceFile, {
    skipFirstLine: true
  })
);
```

This functionality might help to keep the user code cleaner and shorter, but I understand it's a quite specific extra feature you might not want to include and leave to the users.

If it makes sense to you to include it I can try to submit a PR as soon as I have some free time.

**Comment by jahewson** [comment]
Hi, I don't think that byline needs to ship this functionality but thanks for the suggestion.
